name: Install APK

on:
  push:
    branches:
      - main

# env:
#   DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#   DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ env.DOCKERHUB_USERNAME }}
      #     password: ${{ env.DOCKERHUB_TOKEN }}
      # - name: Build Docker image
        # run: |
        #   docker build -t myapp:latest .
      - name: install dependencies
        run: |
          ## install required kernel modules
          apt install adb
          apt install linux-modules-extra-`uname -r`
          modprobe binder_linux devices="binder,hwbinder,vndbinder"
          modprobe ashmem_linux
      - name: install apk
        run: |
          docker run -itd --rm --privileged --pull always -v ~/data:/data -p 5555:5555 redroid/redroid:11.0.0-latest

      - name: install apk
        run: |
          adb connect localhost:5555
          adb install -s example.apk
      
      - name: Upload data
        uses: actions/upload-artifact@v3
        if: always()
        with:
            name: apk_data
            path: data      