name: Install APK

on:
  push:
    branches:
      - main

jobs:
  download-install-and-extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name : install adb
        run: | 
          sudo apt install adb
      - name: install redroid dependencies
        run: |
          ## install required kernel modules          
          sudo apt install linux-modules-extra-`uname -r`
          sudo modprobe binder_linux devices="binder,hwbinder,vndbinder"
          sudo modprobe ashmem_linux          
      - name: run emulator
        run: |
          mkdir data
          docker run -itd --rm --privileged --pull always -v $(pwd)/data:/data -p 5555:5555 redroid/redroid:12.0.0-latest

      - name: adb connect install
        run: |                    
          adb connect localhost:5555
          adb devices -l 
          adb -s localhost:5555 install example.apk          
          # start whatsapp https://stackoverflow.com/questions/59457014/start-whatsapp-chat-using-adb
          adb -s localhost:5555 shell am start -n com.whatsapp/com.whatsapp.Main
          ## adb shell am start -n com.whatsapp/com.whatsapp.Main
          # adb -s localhost:5555 backup -apk com.whatsapp
          # sudo find .
      
      - name: fix data permissions
        if: always()
        run: | 
          # stop docker containers
          docker stop $(docker ps -a -q)
          sudo chown -R runner:runner data
          find data
      
      - name: Upload data
        uses: actions/upload-artifact@v3
        if: always()
        with:
            name: apk_data
            path: data/data      